
-- ALTER VIEW BiView.ListaPrecoCliente_OMT  AS 

SELECT 

	DPT.NAME		AS 'Cliente',  
	X.POSTEDDATE	AS 'Atualizado em',

	PDAT.ITEMRELATION	AS 'Item - Código',
	ERPT.NAME			AS 'Item - Nome',  
	PDAT.UNITID			AS 'Item - Unidade de Medida',  

	PDAT.AMOUNT AS 'Valor', 
	PDAT.CURRENCY AS 'Moeda',
	CONCAT(FORMAT(PDAT.AMOUNT, 'N', 'PT-BR'), ' ', PDAT.CURRENCY) AS 'Valor Formatado'

FROM PRICEDISCADMTRANS PDAT
	JOIN (
		SELECT JOURNALNAME, MAX(JOURNALNUM) AS JOURNALNUM, MAX(POSTEDDATE) AS POSTEDDATE 
		FROM PRICEDISCADMTABLE
		WHERE DATAAREAID = 'OMT' AND POSTED = 1
		GROUP BY JOURNALNAME
	) AS X ON X.JOURNALNUM = PDAT.JOURNALNUM
	JOIN INVENTTABLE IT ON IT.ITEMID = PDAT.ITEMRELATION AND IT.DATAAREAID = PDAT.DATAAREAID
	JOIN ECORESPRODUCT ERP ON ERP.RECID = IT.PRODUCT
	JOIN ECORESPRODUCTTRANSLATION ERPT ON ERPT.PRODUCT = ERP.RECID AND ERPT.LANGUAGEID = 'PT-BR'
	JOIN CUSTTABLE CT ON CT.ACCOUNTNUM = PDAT.ACCOUNTRELATION AND PDAT.ACCOUNTCODE = 0 AND PDAT.MODULE = 1
		OR CT.PRICEGROUP = PDAT.ACCOUNTRELATION
	JOIN DIRPARTYTABLE DPT ON DPT.RECID = CT.PARTY
