
-- ALTER VIEW BiView.AderenciaProducao_Weloze  AS

SELECT P.PRODID AS "Ordem de Produção", 
	CONCAT(I.ITEMID, ' - ', PT.NAME) AS "Nome do Item",
	P.QTYSCHED AS "Quantidade", 
	P.DLVDATE AS "Data Planejada", 
	DATA.MESANO AS "Data de Conclusão (mês/ano)",
	CASE WHEN P.FINISHEDDATE = '1900-01-01' THEN NULL ELSE P.FINISHEDDATE END AS "Data de Conclusão", 
	CASE 
		WHEN P.FINISHEDDATE > P.DLVDATE OR (P.FINISHEDDATE = '1900-01-01' AND P.DLVDATE < CAST(GETDATE() AS DATE)) THEN 'Em atraso'
		ELSE 'Em dia'
	END AS "Situação",
	STATUSOP.STATUS AS "Status"
	--, * 
FROM PRODTABLE P
	JOIN INVENTTABLE I ON I.ITEMID = P.ITEMID AND I.DATAAREAID = P.DATAAREAID
	JOIN ECORESPRODUCT PR ON PR.RECID = I.PRODUCT
	JOIN ECORESPRODUCTTRANSLATION PT ON PT.PRODUCT = PR.RECID AND PT.LANGUAGEID = 'PT-BR'
	CROSS APPLY BiUtil.DataFiltroAnoMes(P.FINISHEDDATE) DATA
	CROSS APPLY BiUtil.StatusOrdemProducao(P.PRODSTATUS) AS STATUSOP

WHERE P.DATAAREAID = 'WELO'
	AND P.FINISHEDDATE <> '1900-01-01'
	--AND P.PRODSTATUS = 5