
-- ALTER VIEW BiView.TransacoesAtivoFixo_Weloze AS 

SELECT 

	X.[Tipo de Documento] AS "Tipo de Documento", 
	
	CASE 
		WHEN X.MODELGROUPID = 'ATIVO'		THEN 'Nosso Ativo em Poder de Terceiro' 
		WHEN X.MODELGROUPID = 'ATIVO TERC'	THEN 'Ativo de Terceiro em Nosso Poder'
	END AS "Tipo de Ativo Imobilizado",

	CONCAT(X.CFOPID, ' - ', X.CFOPNAME) AS "CFOP",
	CONCAT(X.ITEMID, ' - ', X.ITEMNAME) AS "Produto",
	CASE WHEN X.DIRECTION = 1 THEN X.QUANTITY WHEN X.DIRECTION = 2 THEN X.QUANTITY * -1 END AS Saldo,
	CONCAT(X.CODIGO, ' - ', X.CLIENTE) AS "Terceiro",
	
	X.FISCALDOCUMENTDATE AS "Data",
	X.FISCALDOCUMENTNUMBER AS "Nota Fiscal"

FROM 

(
	-- Ordens de Venda (saída ou devolução)

	SELECT 
		'Ordem de Venda' AS "Tipo de Documento",
		IMGI.MODELGROUPID,
		NF.DIRECTION,
		NF.FISCALDOCUMENTACCOUNTNUM AS CODIGO, 
		CF.CFOPID, 
		CF.NAME AS CFOPNAME,  
		LNF.FISCALCLASSIFICATION,
		IT.ITEMID, T.NAME ITEMNAME, 
		S.SALESID AS DOCUMENTOORIGINAL,
		NF.FISCALESTABLISHMENT, 
		NF.FISCALDOCUMENTDATE, 
		DPT.NAME AS CLIENTE, 
		NF.FISCALDOCUMENTNUMBER, 
		NF.THIRDPARTYCNPJCPF, 
		LNF.LINEAMOUNT VALORLINHA, 
		LNF.LINENUM AS NUMLINHA,
		LNF.QUANTITY,
		LNF.UNIT AS UNIDADENF,
		IT.NAMEALIAS	
	FROM FISCALDOCUMENT_BR NF
		JOIN FISCALDOCUMENTLINE_BR LNF ON LNF.FISCALDOCUMENT = NF.RECID
		JOIN CUSTINVOICEJOUR I ON I.RECID = NF.REFRECID AND NF.REFTABLEID = 62
		LEFT JOIN SALESTABLE S ON S.SALESID = I.SALESID
		LEFT JOIN SALESTABLE_BR SBR ON SBR.SALESTABLE = S.RECID
		JOIN CUSTTABLE C ON C.ACCOUNTNUM = NF.FISCALDOCUMENTACCOUNTNUM
		JOIN DIRPARTYTABLE DPT ON DPT.RECID = C.PARTY
		JOIN CFOPTABLE_BR CF ON CF.CFOPID = LNF.CFOP AND CF.DATAAREAID = LNF.DATAAREAID
		JOIN INVENTTABLE IT ON IT.ITEMID = LNF.ITEMID AND IT.DATAAREAID = LNF.DATAAREAID
		JOIN ECORESPRODUCT P ON P.RECID = IT.PRODUCT
		JOIN ECORESPRODUCTTRANSLATION T ON T.PRODUCT = P.RECID
		JOIN LANGUAGETABLE L ON L.LANGUAGEID = T.LANGUAGEID
		JOIN INVENTMODELGROUPITEM IMGI ON IMGI.ITEMDATAAREAID = IT.DATAAREAID AND IMGI.ITEMID = IT.ITEMID
	WHERE 1=1 
		AND LNF.DATAAREAID = 'WELO'
		AND NF.STATUS = 1 -- Status da Nota Fiscal = Aprovado
		AND IMGI.MODELGROUPID IN ('ATIVO', 'ATIVO TERC')	
		AND CF.CFOPID NOT IN ('1.551', '1.556', '2.551', '2.556', '5.551', '6.551', '5.552', '5.910', '6.5552')

	UNION

	-- Ordens de Compra

	SELECT 
		'Ordem de Compra' AS "Tipo de Documento",
		IMGI.MODELGROUPID,
		NF.DIRECTION,
		NF.FISCALDOCUMENTACCOUNTNUM, 
		CF.CFOPID, 
		CF.NAME AS CFOPNAME,  
		LNF.FISCALCLASSIFICATION,
		IT.ITEMID, T.NAME ITEMNAME, 
		P.PURCHID AS DOCUMENTOORIGINAL,
		NF.FISCALESTABLISHMENT, 
		NF.FISCALDOCUMENTDATE, 
		DPT.NAME AS CLIENTE, 
		NF.FISCALDOCUMENTNUMBER, 
		NF.THIRDPARTYCNPJCPF, 
		LNF.LINEAMOUNT VALORLINHA, 
		LNF.LINENUM AS NUMLINHA,
		LNF.QUANTITY,
		LNF.UNIT AS UNIDADENF,
		IT.NAMEALIAS	
	FROM FISCALDOCUMENT_BR NF
		JOIN FISCALDOCUMENTLINE_BR LNF ON LNF.FISCALDOCUMENT = NF.RECID
		JOIN VENDINVOICEJOUR I ON I.RECID = NF.REFRECID AND NF.REFTABLEID = 491
		LEFT JOIN PURCHTABLE P ON P.PURCHID = I.PURCHID
		LEFT JOIN PURCHTABLE_BR PBR ON PBR.PURCHTABLE = P.RECID
		JOIN VENDTABLE V ON V.ACCOUNTNUM = NF.FISCALDOCUMENTACCOUNTNUM
		JOIN DIRPARTYTABLE DPT ON DPT.RECID = V.PARTY
		JOIN CFOPTABLE_BR CF ON CF.CFOPID = LNF.CFOP AND CF.DATAAREAID = LNF.DATAAREAID
		JOIN INVENTTABLE IT ON IT.ITEMID = LNF.ITEMID AND IT.DATAAREAID = LNF.DATAAREAID
		JOIN ECORESPRODUCT PR ON PR.RECID = IT.PRODUCT
		JOIN ECORESPRODUCTTRANSLATION T ON T.PRODUCT = PR.RECID
		JOIN LANGUAGETABLE L ON L.LANGUAGEID = T.LANGUAGEID
		JOIN CUSTTABLE CT ON CT.CNPJCPFNUM_BR = V.CNPJCPFNUM_BR AND CT.DATAAREAID = V.DATAAREAID
		JOIN INVENTMODELGROUPITEM IMGI ON IMGI.ITEMDATAAREAID = IT.DATAAREAID AND IMGI.ITEMID = IT.ITEMID
	WHERE 1=1 
		AND LNF.DATAAREAID = 'WELO'
		AND NF.STATUS = 1 -- Status da Nota Fiscal = Aprovado
		AND IMGI.MODELGROUPID IN ('ATIVO', 'ATIVO TERC')
		AND CF.CFOPID NOT IN ('1.551', '1.556', '2.551', '2.556', '5.551', '6.551', '5.552', '5.910', '6.5552')

	UNION
		
	-- Ordens de Transferência

	SELECT 
		'Ordem de Transferência' AS "Tipo de Documento",
		IMGI.MODELGROUPID,
		NF.DIRECTION,
		CASE WHEN C.ACCOUNTNUM IS NOT NULL THEN C.ACCOUNTNUM ELSE V.ACCOUNTNUM END AS CONTA_TERCEIRO,			
		CF.CFOPID, 
		CF.NAME AS CFOPNAME,  
		LNF.FISCALCLASSIFICATION,
		IT.ITEMID, T.NAME ITEMNAME, 
		S.TRANSFERID AS DOCUMENTOORIGINAL,
		NF.FISCALESTABLISHMENT, 
		NF.FISCALDOCUMENTDATE, 
		CASE WHEN C.ACCOUNTNUM IS NOT NULL THEN PT_C.NAME ELSE PT_V.NAME END AS NOME_TERCEIRO,			
		NF.FISCALDOCUMENTNUMBER, 
		NF.THIRDPARTYCNPJCPF, 
		LNF.LINEAMOUNT VALORLINHA, 
		LNF.LINENUM AS NUMLINHA,
		LNF.QUANTITY,
		LNF.UNIT,
		IT.NAMEALIAS	
	FROM FISCALDOCUMENT_BR NF
		JOIN FISCALDOCUMENTLINE_BR LNF ON LNF.FISCALDOCUMENT = NF.RECID
		JOIN INVENTTRANSFERJOUR I ON I.RECID = NF.REFRECID AND NF.REFTABLEID = 1706
		JOIN INVENTTRANSFERTABLE S ON S.TRANSFERID = I.TRANSFERID
		JOIN INVENTTRANSFERTABLE_CTTE ITT ON ITT.INVENTTRANSFERTABLE = S.RECID
		LEFT JOIN CUSTTABLE C ON C.ACCOUNTNUM = NF.FISCALDOCUMENTACCOUNTNUM AND ITT.CUSTVENDACTYPE = 0
		LEFT JOIN VENDTABLE V ON V.ACCOUNTNUM = NF.FISCALDOCUMENTACCOUNTNUM AND ITT.CUSTVENDACTYPE = 1
		LEFT JOIN DIRPARTYTABLE PT_C ON PT_C.RECID = C.PARTY
		LEFT JOIN DIRPARTYTABLE PT_V ON PT_V.RECID = V.PARTY
		JOIN CFOPTABLE_BR CF ON CF.CFOPID = LNF.CFOP AND CF.DATAAREAID = LNF.DATAAREAID
		JOIN INVENTTABLE IT ON IT.ITEMID = LNF.ITEMID AND IT.DATAAREAID = LNF.DATAAREAID
		JOIN ECORESPRODUCT P ON P.RECID = IT.PRODUCT
		JOIN ECORESPRODUCTTRANSLATION T ON T.PRODUCT = P.RECID
		JOIN LANGUAGETABLE L ON L.LANGUAGEID = T.LANGUAGEID
		JOIN INVENTMODELGROUPITEM IMGI ON IMGI.ITEMDATAAREAID = IT.DATAAREAID AND IMGI.ITEMID = IT.ITEMID
	WHERE 1=1 
		AND LNF.DATAAREAID = 'WELO'
		AND NF.STATUS = 1 -- Status da Nota Fiscal = Aprovado
		AND IMGI.MODELGROUPID IN ('ATIVO', 'ATIVO TERC')
		AND CF.CFOPID NOT IN ('1.551', '1.556', '2.551', '2.556', '5.551', '6.551', '5.552', '5.910', '6.5552')

) AS X
