
--	CONCAT(DATEPART(YEAR, VIT.INVOICEDATE),'/',DATEPART(MONTH, VIT.INVOICEDATE)) AS "FAT MES/ANO",

-- ALTER VIEW [biwelozew3].calculoIDC WITH ENCRYPTION AS 

SELECT 

	CONCAT(DATEPART(YEAR, X.[DT FAT]),'/',DATEPART(MONTH, X.[DT FAT])) AS DATA,
	X.[COD FORN], X.ORGNUMBER, X.STATUS,  
	COUNT(X.[IT FAT]) AS Q

FROM

(
SELECT

	V.ACCOUNTNUM AS "COD FORN",
	CONCAT(V.ACCOUNTNUM, ' - ', PT.NAME) AS FORNECEDOR,
	PT.ORGNUMBER,
	P.PURCHID AS "OC",
	L.LINENUMBER AS "LINHA OC",
	L.ITEMID AS "ITEM OC",
	L.PURCHQTY AS "QTD OC",
	L.LINEAMOUNT AS "VL OC",
	L.DELIVERYDATE AS "DT OC",

	VIT.INVOICEID AS FAT,
	VIT.INVOICEDATE AS "DT FAT", 
	VIT.ITEMID AS "ITEM FAT",
	VIT.QTY AS "IT FAT",
	VIT.QTY AS "QTD FAT",
	VIT.LINEAMOUNT AS "VL FAT",

	/*
	NF.FISCALDOCUMENTNUMBER AS "FAT",
	VIT.ITEMID AS "IT FAT",
	VIT.QTY AS "QTD FAT",
	VIT.LINEAMOUNT AS "VL FAT",
	NF.FISCALDOCUMENTDATE AS "DT FAT",
	*/

	CASE WHEN VIT.INVOICEDATE IS NULL 
		THEN 'Não entregue'
		ELSE
		CASE WHEN VIT.INVOICEDATE <= L.DELIVERYDATE 
			THEN 'No prazo'
			ELSE 'Em atraso'
		END 
	END AS "STATUS"
	
FROM PURCHTABLE P	
	JOIN PURCHTABLE_BR PBR ON PBR.PURCHTABLE = P.RECID
	JOIN PURCHLINE L ON L.PURCHID = P.PURCHID
	
	JOIN INVENTTABLE I	ON I.ITEMID = L.ITEMID	AND I.DATAAREAID = L.DATAAREAID	
	JOIN ECORESPRODUCT PR ON PR.RECID = I.PRODUCT
	OUTER APPLY BI.DimensaoFinanceira(P.DEFAULTDIMENSION, 'ESTABELECIMENTO') AS ESTABELECIMENTO
	JOIN ECORESPRODUCTTRANSLATION T ON T.PRODUCT = PR.RECID
	CROSS APPLY BI.CategoriaOMT(PR.RECID) AS CATEGORIA

	JOIN VENDTABLE V ON V.ACCOUNTNUM = P.INVOICEACCOUNT
	JOIN DIRPARTYTABLE	PT ON PT.RECID = V.PARTY		

	LEFT JOIN SALESPURCHOPERATIONTYPE_BR O ON O.RECID = PBR.SALESPURCHOPERATIONTYPE_BR	
	LEFT JOIN CFOPTABLE_BR CF ON CF.RECID = L.CFOPTABLE_BR
	CROSS APPLY BI.DataFiltroAnoMes(P.CREATEDDATETIME) AS DATAMESANO

	JOIN VENDINVOICETRANS VIT ON VIT.ORIGPURCHID = P.PURCHID AND VIT.ITEMID = L.ITEMID AND VIT.PURCHASELINELINENUMBER = L.LINENUMBER 

WHERE L.DATAAREAID	= 'WELO' AND L.PURCHQTY > 0 AND PT.ORGNUMBER <> '' AND VIT.INVOICEDATE > L.DELIVERYDATE
) 
AS X

GROUP BY X.[COD FORN], X.ORGNUMBER, X.STATUS, CONCAT(DATEPART(YEAR, X.[DT FAT]),'/',DATEPART(MONTH, X.[DT FAT]))
ORDER BY 1, 2, 3, 4, 5