
-- ALTER VIEW biwelozew3.DetalhamentoIDC WITH ENCRYPTION AS

SELECT 
	V.ACCOUNTNUM AS "Fornecedor",
	P.PURCHID AS "Ordem de Compra", 
	L.LINENUMBER AS "Linha", 
	CONCAT(L.ITEMID, ' - ', T.NAME) AS "Item", 
	L.DELIVERYDATE AS "Dt. Prometida", 
	DATEADD(DAY, 3, L.DELIVERYDATE) AS "Dt. Máxima", 
	VIT.INVOICEDATE AS "Dt. Entrada", 
	CASE WHEN VIT.INVOICEDATE > DATEADD(DAY,3, L.DELIVERYDATE) THEN 'EM ATRASO' ELSE 'NO PRAZO' END AS "Status",
	DATAMESANO.MESANO AS "Dt. Entrada (mês/ano)"
FROM PURCHTABLE P	
	JOIN PURCHTABLE_BR PBR ON PBR.PURCHTABLE = P.RECID
	JOIN PURCHLINE L ON L.PURCHID = P.PURCHID
	JOIN INVENTTABLE I	ON I.ITEMID = L.ITEMID	AND I.DATAAREAID = L.DATAAREAID	
	JOIN ECORESPRODUCT PR ON PR.RECID = I.PRODUCT
	OUTER APPLY BI.DimensaoFinanceira(P.DEFAULTDIMENSION, 'ESTABELECIMENTO') AS ESTABELECIMENTO
	JOIN ECORESPRODUCTTRANSLATION T ON T.PRODUCT = PR.RECID AND T.LANGUAGEID = 'PT-BR'
	CROSS APPLY BI.CategoriaOMT(PR.RECID) AS CATEGORIA
	JOIN VENDTABLE V ON V.ACCOUNTNUM = P.INVOICEACCOUNT
	JOIN DIRPARTYTABLE	PT ON PT.RECID = V.PARTY		
	LEFT JOIN SALESPURCHOPERATIONTYPE_BR O ON O.RECID = PBR.SALESPURCHOPERATIONTYPE_BR	
	LEFT JOIN CFOPTABLE_BR CF ON CF.RECID = L.CFOPTABLE_BR	
	JOIN VENDINVOICETRANS VIT ON VIT.ORIGPURCHID = P.PURCHID AND VIT.ITEMID = L.ITEMID AND VIT.PURCHASELINELINENUMBER = L.LINENUMBER 
	CROSS APPLY BI.DataFiltroAnoMes(VIT.INVOICEDATE) AS DATAMESANO

WHERE L.DATAAREAID	= 'WELO' AND L.PURCHQTY > 0 AND PT.ORGNUMBER <> '' 
	--AND V.ACCOUNTNUM = 'WELO-000558'
	--AND CONCAT(DATEPART(YEAR, VIT.INVOICEDATE),'/',DATEPART(MONTH, VIT.INVOICEDATE)) = CONCAT(DATEPART(YEAR, '2016-02-01'),'/',DATEPART(MONTH, '2016-02-01'))
	--AND DATEADD(DAY, -3, VIT.INVOICEDATE) > L.DELIVERYDATE
	--ORDER BY 1, 2, 3, 4
