
-- ALTER VIEW [BiView].[OrdensCompra_Weloze]  AS 

SELECT 

	S.PURCHID AS "Ordem de Compra - Número",
	STATUS.STATUS AS "Ordem de Compra - Status",
	S.PAYMENT AS "Ordem de Compra - Condição de Pagamento",

	CASE WHEN REMAINPURCHPHYSICAL > 0 THEN 'Sim' ELSE 'Não' END AS "Ordem de Compra - Pendente",

	CASE ESTABELECIMENTO.VALOR 
		WHEN NULL THEN 'Não definido' 
		ELSE ESTABELECIMENTO.VALOR 
	END AS Estabelecimento,

	CONVERT(DATETIME, CONVERT(VARCHAR, S.CREATEDDATETIME , 101))	AS "Data de Criação",
	CONCAT('Semana ', DATEPART(ISO_WEEK, S.CREATEDDATETIME))		AS "Data de Criação - Nº da Semana",
	DATAMESANO.MESANO AS "Data de Criação - Mês/Ano",

	L.DELIVERYDATE AS "Data de Entrega",
	ENTREGA.MESANO AS "Data de Entrega - Mês/Ano",
	
	C.CNPJCPFNUM_BR AS "Fornecedor - CNPJ",
	C.ACCOUNTNUM	AS "Fornecedor - Código",
	PT.NAME			AS "Fornecedor - Nome",
	CONCAT(C.ACCOUNTNUM, ' - ', PT.NAME) AS "Fornecedor - Código e Nome",

	O.OPERATIONTYPEID AS "Tipo de Operaçao",

	CF.CFOPID	AS "CFOP - Código",  
	CF.NAME		AS "CFOP - Nome",
	CONCAT(CF.CFOPID, ' - ', CF.NAME)	AS "CFOP - Código e Nome",

	I.ITEMID						AS "Item - Código",
	T.NAME							AS "Item - Nome",
	CONCAT(I.ITEMID, ' - ', T.NAME) AS "Item - Código e Nome",
	CATEGORIA.CATEGORIA				AS "Item - Categoria",

	L.CURRENCYCODE AS "Moeda",
	CASE WHEN L.CURRENCYCODE = 'BRL' THEN 1.0 ELSE CAMBIOATUAL.TAXA END AS "Tx. de Câmbio Atual",

	D.INVENTBATCHID AS		"Dimensão - Lote",
	D.INVENTCOLORID AS		"Dimensão - Cor",
	D.INVENTLOCATIONID AS	"Dimensão - Depósito",
	D.INVENTSERIALID AS		"Dimensão - Número de Série",
	D.INVENTSITEID AS		"Dimensão - Site",
	D.INVENTSIZEID AS		"Dimensão - Tensão",
	D.INVENTSTYLEID AS		"Dimensão - Largura da Lâmina",
	D.WMSLOCATIONID AS		"Dimensão - Localização",

	L.PURCHQTY				AS "Quantidade Total",
	L.REMAINPURCHPHYSICAL	AS "Quantidade Pendente",

	CAMBIOATUAL.TAXA,
	(L.LINEAMOUNT + COALESCE(IPI.VALOR, 0) + COALESCE(ENCARGO.VALOR, 0)) * (CASE WHEN L.CURRENCYCODE = 'BRL' THEN 1.0 ELSE CAMBIOATUAL.TAXA END) AS	"Valor Bruto",
	(L.LINEAMOUNT + COALESCE(IPI.VALOR, 0)) * (CASE WHEN L.CURRENCYCODE = 'BRL' THEN 1.0 ELSE CAMBIOATUAL.TAXA END) AS								"Valor Bruto s/ Encargos",
	(L.LINEAMOUNT + COALESCE(ENCARGO.VALOR, 0)) * (CASE WHEN L.CURRENCYCODE = 'BRL' THEN 1.0 ELSE CAMBIOATUAL.TAXA END) AS							"Valor Bruto s/ IPI",

	COALESCE(ENCARGO.VALOR, 0) * (CASE WHEN L.CURRENCYCODE = 'BRL' THEN 1.0 ELSE CAMBIOATUAL.TAXA END) AS	"Valor Encargos",

	COALESCE(IPI.VALOR, 0) * (CASE WHEN L.CURRENCYCODE = 'BRL' THEN 1.0 ELSE CAMBIOATUAL.TAXA END) AS		"Valor IPI",
	COALESCE(PIS.VALOR, 0) * (CASE WHEN L.CURRENCYCODE = 'BRL' THEN 1.0 ELSE CAMBIOATUAL.TAXA END) AS		"Valor PIS",
	COALESCE(ICMS.VALOR, 0) * (CASE WHEN L.CURRENCYCODE = 'BRL' THEN 1.0 ELSE CAMBIOATUAL.TAXA END) AS		"Valor ICMS",
	COALESCE(COFINS.VALOR, 0) * (CASE WHEN L.CURRENCYCODE = 'BRL' THEN 1.0 ELSE CAMBIOATUAL.TAXA END) AS	"Valor COFINS",
	COALESCE(ISSQN.VALOR, 0) * (CASE WHEN L.CURRENCYCODE = 'BRL' THEN 1.0 ELSE CAMBIOATUAL.TAXA END) AS		"Valor ISSQN",

	(L.LINEAMOUNT + COALESCE(ENCARGO.VALOR, 0) - COALESCE(PIS.VALOR, 0) - COALESCE(COFINS.VALOR, 0) - COALESCE(ICMS.VALOR, 0) - COALESCE(ISSQN.VALOR, 0)) * (CASE WHEN L.CURRENCYCODE = 'BRL' THEN 1.0 ELSE CAMBIOATUAL.TAXA END) AS "Valor Líquido",

	((L.LINEAMOUNT + COALESCE(IPI.VALOR, 0) + COALESCE(ENCARGO.VALOR, 0)) / L.PURCHQTY * L.REMAINPURCHPHYSICAL) * (CASE WHEN L.CURRENCYCODE = 'BRL' THEN 1.0 ELSE CAMBIOATUAL.TAXA END) AS "Valor Bruto Pendente",
	((L.LINEAMOUNT + COALESCE(IPI.VALOR, 0)) / L.PURCHQTY * L.REMAINPURCHPHYSICAL) * (CASE WHEN L.CURRENCYCODE = 'BRL' THEN 1.0 ELSE CAMBIOATUAL.TAXA END) AS "Valor Bruto s/ Encargos Pendente",
	((L.LINEAMOUNT + COALESCE(ENCARGO.VALOR, 0)) / L.PURCHQTY * L.REMAINPURCHPHYSICAL) * (CASE WHEN L.CURRENCYCODE = 'BRL' THEN 1.0 ELSE CAMBIOATUAL.TAXA END) AS "Valor Bruto s/ IPI Pendente",
	(COALESCE(ENCARGO.VALOR, 0) / L.PURCHQTY * L.REMAINPURCHPHYSICAL) * (CASE WHEN L.CURRENCYCODE = 'BRL' THEN 1.0 ELSE CAMBIOATUAL.TAXA END) AS "Valor Encargos Pendente",
	(COALESCE(IPI.VALOR, 0) / L.PURCHQTY * L.REMAINPURCHPHYSICAL) * (CASE WHEN L.CURRENCYCODE = 'BRL' THEN 1.0 ELSE CAMBIOATUAL.TAXA END) AS "Valor IPI Pendente",
	(COALESCE(PIS.VALOR, 0) / L.PURCHQTY * L.REMAINPURCHPHYSICAL) * (CASE WHEN L.CURRENCYCODE = 'BRL' THEN 1.0 ELSE CAMBIOATUAL.TAXA END) AS "Valor PIS Pendente",
	(COALESCE(ICMS.VALOR, 0) / L.PURCHQTY * L.REMAINPURCHPHYSICAL) * (CASE WHEN L.CURRENCYCODE = 'BRL' THEN 1.0 ELSE CAMBIOATUAL.TAXA END) AS "Valor ICMS Pendente",
	(COALESCE(COFINS.VALOR, 0) / L.PURCHQTY * L.REMAINPURCHPHYSICAL) * (CASE WHEN L.CURRENCYCODE = 'BRL' THEN 1.0 ELSE CAMBIOATUAL.TAXA END) AS "Valor COFINS Pendente",
	((COALESCE(ISSQN.VALOR, 0)) / L.PURCHQTY * L.REMAINPURCHPHYSICAL) * (CASE WHEN L.CURRENCYCODE = 'BRL' THEN 1.0 ELSE CAMBIOATUAL.TAXA END) AS "Valor ISSQN Pendente",
	((L.LINEAMOUNT + COALESCE(ENCARGO.VALOR, 0) - COALESCE(PIS.VALOR, 0) - COALESCE(COFINS.VALOR, 0) - COALESCE(ICMS.VALOR, 0) - COALESCE(ISSQN.VALOR, 0)) / L.PURCHQTY * L.REMAINPURCHPHYSICAL) * (CASE WHEN L.CURRENCYCODE = 'BRL' THEN 1.0 ELSE CAMBIOATUAL.TAXA END) AS "Valor Líquido Pendente"

FROM PURCHTABLE S	
	JOIN PURCHTABLE_BR SBR ON SBR.PURCHTABLE = S.RECID
	JOIN PURCHLINE L ON L.PURCHID = S.PURCHID	
	--JOIN PURCHTABLE_BR LBR ON LBR.PURCHTABLE = L.RECID
	JOIN INVENTTABLE i	ON I.ITEMID = L.ITEMID	AND I.DATAAREAID = L.DATAAREAID	
	JOIN ECORESPRODUCT PR ON PR.RECID = I.PRODUCT
	OUTER APPLY BI.DimensaoFinanceira(S.DEFAULTDIMENSION, 'ESTABELECIMENTO') AS ESTABELECIMENTO
	JOIN VENDTABLE C ON C.ACCOUNTNUM = S.ORDERACCOUNT	
	JOIN DIRPARTYTABLE	PT ON PT.RECID = C.PARTY		
	LEFT JOIN SALESPURCHOPERATIONTYPE_BR O ON O.RECID = SBR.SALESPURCHOPERATIONTYPE_BR	
	LEFT JOIN CFOPTABLE_BR CF ON CF.RECID = L.CFOPTABLE_BR
	JOIN ECORESPRODUCTTRANSLATION T ON T.PRODUCT = PR.RECID
	LEFT JOIN MARKUPTRANS M ON M.TRANSRECID = L.RECID AND M.TRANSTABLEID = 359
	JOIN INVENTDIM D ON D.INVENTDIMID = L.INVENTDIMID

	CROSS APPLY BI.DataFiltroAnoMes(S.CREATEDDATETIME) AS DATAMESANO
	CROSS APPLY BI.CategoriaOMT(PR.RECID) AS CATEGORIA
	CROSS APPLY BiUtil.StatusOrdemCompra (S.PURCHSTATUS) AS STATUS
	CROSS APPLY BI.DataFiltroAnoMes(L.DELIVERYDATE) AS ENTREGA	

	OUTER APPLY BiUtil.EncargoLinhaOrdemCompra (L.RECID) AS ENCARGO
	OUTER APPLY BiUtil.ImpostoPorGrupos (S.DATAAREAID, L.TAXGROUP, L.TAXITEMGROUP, 2, L.LINEAMOUNT) AS ICMS
	OUTER APPLY BiUtil.ImpostoPorGrupos (S.DATAAREAID, L.TAXGROUP, L.TAXITEMGROUP, 8, L.LINEAMOUNT) AS IPI
	OUTER APPLY BiUtil.ImpostoPorGrupos (S.DATAAREAID, L.TAXGROUP, L.TAXITEMGROUP, 1, L.LINEAMOUNT) AS PIS
	OUTER APPLY BiUtil.ImpostoPorGrupos (S.DATAAREAID, L.TAXGROUP, L.TAXITEMGROUP, 3, L.LINEAMOUNT) AS COFINS
	OUTER APPLY BiUtil.ImpostoPorGrupos (S.DATAAREAID, L.TAXGROUP, L.TAXITEMGROUP, 4, L.LINEAMOUNT) AS ISSQN
	OUTER APPLY BiUtil.TaxaCambioAtual(L.CURRENCYCODE) AS CAMBIOATUAL

WHERE L.DATAAREAID	= 'WELO' AND L.PURCHQTY != 0
	AND (
		O.CREATEFINANCIALTRANS = 1 
		AND O.OPERATIONTYPEID NOT IN (
			'E1201/2201', 'DV1201/2201', 'E201/202', -- devolução de venda
			'E1406/2406', 'E1551/2551' -- compra do ativo imobilizado
		)
	)
AND S.PURCHSTATUS != 4 -- Cancelada
AND S.PURCHASETYPE != 4 -- Ordem devolvida

