
-- ALTER VIEW BiView.InstrucoesProducao_Weloze AS 

SELECT 

	CONCAT(PT.PRODID, ' ', IT.ITEMID, ' - ', PT.NAME) AS "Ordem de Produção",
	CONCAT(PR.OPRNUM, ' - ', PR.OPRID, ' (', (PR.OPRPRIORITY + 1), 'ª)') AS "Operação",
	DR.NOTES AS "Instruções"

FROM PRODTABLE PT
	JOIN PRODROUTE PR ON PR.PRODID = PT.PRODID AND PR.DATAAREAID = PT.DATAAREAID
	JOIN INVENTTABLE IT ON IT.ITEMID = PT.ITEMID AND IT.DATAAREAID = PT.DATAAREAID 
	JOIN ECORESPRODUCT ERP ON ERP.RECID = IT.PRODUCT
	JOIN ECORESPRODUCTTRANSLATION ERPT ON ERPT.PRODUCT = ERP.RECID AND ERPT.LANGUAGEID = 'PT-BR'
	LEFT JOIN DOCUREF DR ON DR.REFRECID = PR.RECID AND DR.REFCOMPANYID = PR.DATAAREAID AND DR.REFTABLEID = 257 -- ProdRoute
	
WHERE PT.DATAAREAID = 'WELO' 

AND PT.CREATEDDATETIME > DATEADD(MONTH, -2, GETDATE())