
CREATE VIEW BiView.ListaRecursos_Weloze AS 

SELECT 

	CONCAT(WCT.WRKCTRID, ' - ', WCT.NAME) AS "Recurso",
	WCT.INVENTLOCATIONID AS	"Depósito",
	WCT.WMSLOCATIONID AS "Localização",
	CONCAT(WCT.INVENTLOCATIONID , ' ', WCT.WMSLOCATIONID) AS "Localização Completa"

FROM WRKCTRTABLE WCT
	
WHERE WCT.DATAAREAID = 'WELO'