
CREATE FUNCTION BiUtil.CategoriaHierarquiaOMT (@EcoResProductRecId BIGINT)
RETURNS TABLE AS

	RETURN (SELECT REPLACE(
					SUBSTRING(
						X.CATEGORIA, 
						CHARINDEX(	'HIERARQUIA GRUPO WELOZE/HIERARQUIA OMT/', X.CATEGORIA), LEN(X.CATEGORIA) + 1) , 
									'HIERARQUIA GRUPO WELOZE/HIERARQUIA OMT/', 
					'') AS CATEGORIA FROM
			(SELECT CASE WHEN C0.NAME IS NULL
					THEN 'Sem Categoria' 
				ELSE 
					CONCAT(C9.NAME, '/', C8.NAME, '/', C7.NAME, '/', C6.NAME, '/', C5.NAME, '/', C4.NAME, '/', C3.NAME, '/', C2.NAME, '/', C1.NAME, '/', C0.NAME) 
				END AS CATEGORIA
			FROM ECORESPRODUCT P
				LEFT JOIN ECORESPRODUCTCATEGORY PC ON PC.PRODUCT = P.RECID
				LEFT JOIN ECORESCATEGORYHIERARCHY ERCH ON ERCH.RECID = PC.CATEGORYHIERARCHY
				LEFT JOIN ECORESCATEGORY	C0	ON PC.CATEGORY		 = C0.RECID
				LEFT JOIN ECORESCATEGORY	C1	ON C0.PARENTCATEGORY = C1.RECID
				LEFT JOIN ECORESCATEGORY	C2	ON C1.PARENTCATEGORY = C2.RECID
				LEFT JOIN ECORESCATEGORY	C3	ON C2.PARENTCATEGORY = C3.RECID
				LEFT JOIN ECORESCATEGORY	C4	ON C3.PARENTCATEGORY = C4.RECID
				LEFT JOIN ECORESCATEGORY	C5	ON C4.PARENTCATEGORY = C5.RECID
				LEFT JOIN ECORESCATEGORY	C6	ON C5.PARENTCATEGORY = C6.RECID
				LEFT JOIN ECORESCATEGORY	C7	ON C6.PARENTCATEGORY = C7.RECID
				LEFT JOIN ECORESCATEGORY	C8	ON C7.PARENTCATEGORY = C8.RECID
				LEFT JOIN ECORESCATEGORY	C9	ON C8.PARENTCATEGORY = C9.RECID
			WHERE P.RECID = @EcoResProductRecId AND ERCH.NAME = 'HIERARQUIA GRUPO WELOZE'
			) AS X);


