
ALTER FUNCTION [BiUtil].[DataFiltro] (@Data DATETIME) 
RETURNS TABLE AS 

	RETURN (
		SELECT 
			CONCAT(DATEPART(YEAR, @Data), '/', RIGHT(CONCAT('0', DATEPART(MONTH, @Data)), 2)) AS MES_ANO,
			CONCAT(DATEPART(YEAR, @Data), ' - Semana ', RIGHT(CONCAT('0', DATEPART(ISO_WEEK, @Data)), 2)) AS SEMANA_ANO,
			@Data AS DIA_MES_ANO	
	) 


GO


