
ALTER FUNCTION BiUtil.DimensaoFinanceira (@DimensionId BIGINT, @DimensionName VARCHAR(100))
RETURNS TABLE AS

	RETURN (SELECT TOP 1 DFT.DESCRIPTION AS VALOR
		FROM DIMENSIONATTRIBUTEVALUESETITEM DAVSI
			JOIN DIMENSIONATTRIBUTEVALUE DAV ON DAV.RECID = DAVSI.DIMENSIONATTRIBUTEVALUE
			JOIN DIMENSIONATTRIBUTE DA ON DA.RECID = DAV.DIMENSIONATTRIBUTE
			LEFT JOIN DIMENSIONATTRIBUTEDIRCATEGORY DADC ON DADC.DIMENSIONATTRIBUTE = DA.RECID
			LEFT JOIN DIMENSIONFINANCIALTAG DFT ON DFT.FINANCIALTAGCATEGORY = DADC.DIRCATEGORY AND DFT.RECID = DAV.ENTITYINSTANCE 
			LEFT JOIN DIMATTRIBUTECUSTTABLE DACT ON DACT.VALUE = DAVSI.DISPLAYVALUE	AND DACT.RECID = DAV.ENTITYINSTANCE
			LEFT JOIN DIMATTRIBUTEPROJTABLE DAPT ON DAPT.VALUE = DAVSI.DISPLAYVALUE AND DAPT.RECID = DAV.ENTITYINSTANCE
		WHERE DAVSI.DIMENSIONATTRIBUTEVALUESET = @DimensionId AND DA.NAME = @DimensionName);

