
ALTER FUNCTION BiUtil.FatorConversaoUnidades (@UnidadeOrigem VARCHAR(5), @UnidadeDestino VARCHAR(5), @Product BIGINT)
RETURNS TABLE  AS

RETURN 

	(
	SELECT 
		TOP 1 
		FACTOR * NUMERATOR / DENOMINATOR AS FATOR
	FROM UnitOfMeasureConversion C 
		JOIN UNITOFMEASURE UO ON UO.RECID = FROMUNITOFMEASURE
		JOIN UNITOFMEASURE UD ON UD.RECID = TOUNITOFMEASURE
		LEFT JOIN ECORESPRODUCT P ON P.RECID = C.PRODUCT
	WHERE 1=1 
		AND RTRIM(LTRIM(UPPER(UO.SYMBOL))) = RTRIM(LTRIM(UPPER(@UnidadeOrigem))) 
		AND RTRIM(LTRIM(UPPER(UD.SYMBOL))) = RTRIM(LTRIM(UPPER(@UnidadeDestino)))
		AND C.PRODUCT IN (0, 1)
	ORDER BY C.PRODUCT DESC
	) 
