
ALTER FUNCTION BiUtil.FatorConversaoUnidades (@UnidadeOrigem VARCHAR(5), @UnidadeDestino VARCHAR(5), @Product BIGINT)
RETURNS TABLE  AS

RETURN 

	(
		SELECT TOP 1 * FROM 
		( 
			SELECT 
				FACTOR * NUMERATOR / DENOMINATOR AS FATOR, C.PRODUCT
			FROM UnitOfMeasureConversion C 
				JOIN UNITOFMEASURE UO ON UO.RECID = FROMUNITOFMEASURE
				JOIN UNITOFMEASURE UD ON UD.RECID = TOUNITOFMEASURE
			WHERE 1=1 
				AND (C.PRODUCT IS NULL OR C.PRODUCT = @Product)
				AND RTRIM(LTRIM(UPPER(UO.SYMBOL))) = RTRIM(LTRIM(UPPER(@UnidadeOrigem))) 
				AND RTRIM(LTRIM(UPPER(UD.SYMBOL))) = RTRIM(LTRIM(UPPER(@UnidadeDestino)))
			UNION
			SELECT 
				1 / (FACTOR * NUMERATOR / DENOMINATOR) AS FATOR, C.PRODUCT
			FROM UnitOfMeasureConversion C 
				JOIN UNITOFMEASURE UO ON UO.RECID = FROMUNITOFMEASURE
				JOIN UNITOFMEASURE UD ON UD.RECID = TOUNITOFMEASURE
			WHERE 1=1 
				AND (C.PRODUCT IS NULL OR C.PRODUCT = @Product)
				AND RTRIM(LTRIM(UPPER(UD.SYMBOL))) = RTRIM(LTRIM(UPPER(@UnidadeOrigem))) 
				AND RTRIM(LTRIM(UPPER(UO.SYMBOL))) = RTRIM(LTRIM(UPPER(@UnidadeDestino)))
			) AS X
		ORDER BY X.PRODUCT DESC
	) 
