
ALTER FUNCTION [BiUtil].TaxaCambioAtual (@MoedaEstrangeira VARCHAR(5)) 
RETURNS TABLE AS
RETURN 
(
	SELECT 
		(ER.EXCHANGERATE / 100.0 * FATOR.VALOR) AS TAXA 
	FROM EXCHANGERATECURRENCYPAIR ERCP
		JOIN EXCHANGERATE ER ON ER.EXCHANGERATECURRENCYPAIR = ERCP.RECID
		JOIN EXCHANGERATETYPE ERT ON ERT.RECID = ERCP.EXCHANGERATETYPE
		CROSS APPLY biweloze.FatorExibicaoTaxaCambio(ERCP.EXCHANGERATEDISPLAYFACTOR) AS FATOR
	WHERE TOCURRENCYCODE = 'BRL' AND ERT.NAME = 'Padrão' AND ER.VALIDTO = '2154-12-31'
		AND ERCP.FROMCURRENCYCODE = @MoedaEstrangeira
)

