
-- ALTER VIEW BiView .EntregaFornecedores_Weloze  AS

SELECT 
	
	CONCAT(V.ACCOUNTNUM, ' - ', PT.NAME)	AS "Fornecedor",
	P.PURCHID								AS "Ordem de Compra", 
	L.LINENUMBER							AS "N� Linha", 
	CONCAT(L.ITEMID, ' - ', T.NAME)			AS "Nome do Item", 

	L.DELIVERYDATE						AS "Dt. Prometida", 
	DATEADD(DAY, 3, L.DELIVERYDATE)		AS "Dt. M�xima", 
	VIT.INVOICEDATE						AS "Dt. Entrada", 
	DATAMESANO.MESANO					AS "Dt. Entrada (m�s/ano)",

	CASE WHEN VIT.INVOICEDATE > DATEADD(DAY,3, L.DELIVERYDATE) 
		THEN 'Em atraso' 
		ELSE 'No prazo' 
	END AS "Status"	
	
FROM PURCHTABLE P	
	JOIN PURCHTABLE_BR PBR ON PBR.PURCHTABLE = P.RECID
	JOIN PURCHLINE L ON L.PURCHID = P.PURCHID
	JOIN INVENTTABLE I	ON I.ITEMID = L.ITEMID	AND I.DATAAREAID = L.DATAAREAID	
	JOIN ECORESPRODUCT PR ON PR.RECID = I.PRODUCT
	OUTER APPLY BiUtil.DimensaoFinanceira(P.DEFAULTDIMENSION, 'ESTABELECIMENTO') AS ESTABELECIMENTO
	JOIN ECORESPRODUCTTRANSLATION T ON T.PRODUCT = PR.RECID AND T.LANGUAGEID = 'PT-BR'
	OUTER APPLY BiUtil.CategoriaOMT(PR.RECID) AS CATEGORIA
	JOIN VENDTABLE V ON V.ACCOUNTNUM = P.INVOICEACCOUNT
	JOIN DIRPARTYTABLE	PT ON PT.RECID = V.PARTY		
	LEFT JOIN SALESPURCHOPERATIONTYPE_BR O ON O.RECID = PBR.SALESPURCHOPERATIONTYPE_BR	
	LEFT JOIN CFOPTABLE_BR CF ON CF.RECID = L.CFOPTABLE_BR	
	JOIN VENDINVOICETRANS VIT ON VIT.ORIGPURCHID = P.PURCHID AND VIT.ITEMID = L.ITEMID AND VIT.PURCHASELINELINENUMBER = L.LINENUMBER 
	CROSS APPLY BiUtil.DataFiltroAnoMes(VIT.INVOICEDATE) AS DATAMESANO

WHERE L.DATAAREAID	= 'WELO' AND L.PURCHQTY > 0
