
-- ALTER VIEW biwelozew3.ext_omt_vw_terceiros_AX  WITH ENCRYPTION AS

SELECT 

	CAST(P.ORGNUMBER AS NUMERIC) AS Codigo, 
	P.NAME AS RazaoSocial, 	
	P.NAMEALIAS AS NomeFantasia, 
	CASE WHEN TELEFONE.DESCRIPTION != '' THEN TELEFONE.DESCRIPTION ELSE EMAIL.DESCRIPTION END AS PessoaContato,
	TELEFONE.LOCATOR AS TelefoneContato,
	EMAIL.LOCATOR AS EmailContato,

	'Fornecedor' AS Tipo, 
	V.ACCOUNTNUM AS CodigoAX,

	ENDERECO.STREET AS Rua, 
	ENDERECO.STREETNUMBER AS Numero, 
	ENDERECO.BUILDINGCOMPLIMENT AS Complemento, 
	ENDERECO.DISTRICTNAME AS Bairro, 
	ENDERECO.CITY AS Cidade, 
	ENDERECO.STATE AS Estado, 
	ENDERECO.ZIPCODE AS CEP,

	V.DATAAREAID
	
FROM VENDTABLE V
	LEFT JOIN DIRPARTYTABLE P ON P.RECID = V.PARTY
	LEFT JOIN LOGISTICSELECTRONICADDRESS EMAIL ON EMAIL.RECID = P.PRIMARYCONTACTEMAIL
	LEFT JOIN LOGISTICSELECTRONICADDRESS TELEFONE ON TELEFONE.RECID = P.PRIMARYCONTACTPHONE
	LEFT JOIN DIRPARTYPOSTALADDRESSVIEW ENDERECO ON ENDERECO.PARTY = V.PARTY AND VALIDFROM <= GETDATE() AND VALIDTO >= GETDATE() AND ENDERECO.ISPRIMARY = 1
WHERE P.ORGNUMBER <> '' AND P.ORGNUMBER IS NOT NULL
AND V.DATAAREAID = 'OMT'

