
-- ALTER VIEW biwelozew3.ext_wlz_vw_produtos_AX AS

SELECT 

	IT.ITEMID AS "Codigo", 
	ERPT.NAME AS "Descricao", 
	ITM.UNITID AS "Unidade_Venda", 
	0 AS "Preco1",
	0 AS "Preco2",
	IT.NETWEIGHT AS "Peso_Liquido"

FROM ECORESPRODUCT ERP
	JOIN ECORESPRODUCTTRANSLATION ERPT ON ERPT.PRODUCT = ERP.RECID AND ERPT.LANGUAGEID = 'PT-BR'
	JOIN INVENTTABLE IT ON IT.PRODUCT = ERP.RECID
	JOIN INVENTTABLEMODULE ITM ON ITM.ITEMID = IT.ITEMID AND ITM.DATAAREAID = IT.DATAAREAID AND ITM.MODULETYPE = 2 -- Venda
	JOIN INVENTITEMGROUPITEM IIGI ON IIGI.ITEMID = IT.ITEMID AND IIGI.ITEMDATAAREAID = IT.DATAAREAID

WHERE IT.DATAAREAID = 'WELO' AND IIGI.ITEMGROUPID IN ('040', '110', '130', '170')
