
-- ALTER VIEW biwelozew3.ext_omt_vw_empresas_AX AS

SELECT 

	'Cliente'			AS "Tipo",
	DPT.NAME			AS "Razao", 
	DPT.NAMEALIAS		AS "Nome_Fantasia", 
	CT.IENUM_BR			AS "CGC_TE", 
	CT.CNPJCPFNUM_BR	AS "CGC_MF",
	
	LPA.STREETNUMBER	AS "NUMERO",

	LPA.STREET			AS "Rua",
	LPA.CITY			AS "Cidade",
	LPA.DISTRICTNAME	AS "Bairro",
	LPA.ZIPCODE			AS "CEP",
	LPA.STATE			AS "UF",
	''					AS "Codigo_Representante"
	
 FROM CUSTTABLE CT
	JOIN DIRPARTYTABLE DPT ON DPT.RECID = CT.PARTY
	JOIN LOGISTICSLOCATION LL ON LL.RECID = DPT.PRIMARYADDRESSLOCATION
	JOIN LOGISTICSPOSTALADDRESS LPA ON LPA.LOCATION = LL.RECID AND CONVERT(DATE, GETDATE()) BETWEEN LPA.VALIDFROM AND LPA.VALIDTO
WHERE CT.DATAAREAID = 'OMT'

UNION

SELECT 

	'Fornecedor'		AS "Tipo",
	DPT.NAME			AS "Razao", 
	DPT.NAMEALIAS		AS "Nome_Fantasia", 
	VT.IENUM_BR			AS "CGC_TE", 
	VT.CNPJCPFNUM_BR	AS "CGC_MF",
	
	LPA.STREETNUMBER	AS "NUMERO",

	LPA.STREET			AS "Rua",
	LPA.CITY			AS "Cidade",
	LPA.DISTRICTNAME	AS "Bairro",
	LPA.ZIPCODE			AS "CEP",
	LPA.STATE			AS "UF",
	''					AS "Codigo_Representante"
	
 FROM VENDTABLE VT
	JOIN DIRPARTYTABLE DPT ON DPT.RECID = VT.PARTY
	JOIN LOGISTICSLOCATION LL ON LL.RECID = DPT.PRIMARYADDRESSLOCATION
	JOIN LOGISTICSPOSTALADDRESS LPA ON LPA.LOCATION = LL.RECID AND CONVERT(DATE, GETDATE()) BETWEEN LPA.VALIDFROM AND LPA.VALIDTO
WHERE VT.DATAAREAID = 'OMT'
