
-- ALTER VIEW BiView.ConsumoMateriaPrimaTerceiro_Weloze AS

SELECT 	

	L.TRANSDATE AS "Data", 
	DATA.MESANO AS "Data (ano/mês)",
	II.ITEMGROUPID AS "Grupo",
	P.PRODID AS "Ordem de Produção",
	
	CONCAT(L.ITEMID, ' - ', PT.NAME) AS "Item",
	PR.SEARCHNAME AS "Item - Nome de Pesquisa",
	L.BOMCONSUMP AS "Consumo", 
	
	CASE WHEN L.BOMUNITID = 'Kg' 
		THEN 1.0 
		ELSE I.NETWEIGHT 
	END AS "Peso",
	
	CASE WHEN L.BOMUNITID = 'Kg' 
		THEN L.BOMCONSUMP 
		ELSE L.BOMCONSUMP * I.NETWEIGHT 
	END  AS "Total"

FROM PRODJOURNALBOM L
	JOIN PRODJOURNALTABLE T ON T.JOURNALID = L.JOURNALID AND T.JOURNALTYPE = 0
	JOIN INVENTDIM D ON D.INVENTDIMID = L.INVENTDIMID
	JOIN PRODTABLE P ON P.PRODID = L.PRODID
	JOIN INVENTTABLE I ON I.ITEMID = L.ITEMID AND I.DATAAREAID = L.DATAAREAID
	JOIN ECORESPRODUCT PR ON PR.RECID = I.PRODUCT
	JOIN ECORESPRODUCTTRANSLATION PT ON PT.PRODUCT = PR.RECID AND PT.LANGUAGEID = 'PT-BR'
	CROSS APPLY BiUtil.DataFiltroAnoMes(L.TRANSDATE) DATA
	JOIN INVENTITEMGROUPITEM II ON II.ITEMDATAAREAID = I.DATAAREAID AND II.ITEMID = I.ITEMID
WHERE II.ITEMGROUPID IN ('150')
	AND T.POSTED = 1
	AND T.DATAAREAID = 'WELO'
	AND L.BOMCONSUMP <> 0
