
 -- ALTER VIEW BiView.AnaliseMargem_OMT AS 

SELECT 

	CONCAT(SPOT.OPERATIONTYPEID, ' - ', SPOT.NAME)	AS "Tipo de Operação",

	CONCAT(CT.ACCOUNTNUM, ' - ', DPT.NAME)	AS "Cliente",
	CIT.INVOICEDATE			AS "Data",
	CIT.INVOICEID			AS "Fatura",
	CIT.ITEMID				AS "Item",
	CUSTO.INVENTTRANSID
	
FROM CUSTINVOICETRANS CIT
	JOIN CUSTINVOICEJOUR CIJ ON CIJ.SALESID = CIT.SALESID 
		AND CIJ.INVOICEID = CIT.INVOICEID
		AND CIJ.INVOICEDATE = CIT.INVOICEDATE
		AND CIJ.NUMBERSEQUENCEGROUP = CIT.NUMBERSEQUENCEGROUP
	JOIN CUSTTABLE CT ON CT.ACCOUNTNUM = CIJ.ORDERACCOUNT
	JOIN DIRPARTYTABLE DPT ON DPT.RECID = CT.PARTY
	
	LEFT JOIN (
	
		SELECT 

		CIT.DATAAREAID, CIT.RECID, CIT.INVENTTRANSID,
		
		(SUM(IT.COSTAMOUNTPOSTED) + SUM(COSTAMOUNTADJUSTMENT) ) / SUM(CIT.QTY) AS CUSTO_UNITARIO,
		SUM(CIT.QTY) AS QUANTIDADE,
		SUM(IT.COSTAMOUNTPOSTED) + SUM(COSTAMOUNTADJUSTMENT) CUSTO_TOTAL

		FROM CUSTINVOICETRANS CIT 				
			LEFT JOIN INVENTTRANSORIGIN ITO ON ITO.INVENTTRANSID = CIT.INVENTTRANSID
			LEFT JOIN INVENTTRANS IT ON IT.INVENTTRANSORIGIN = ITO.RECID 
				AND IT.DATEFINANCIAL = CIT.INVOICEDATE 
				AND IT.INVOICEID = CIT.INVOICEID
				--AND IT.QTY <> 0
				AND IT.PACKINGSLIPRETURNED = 0
				AND IT.STATUSRECEIPT IN (0, 1)
				AND IT.STATUSISSUE IN (0, 1)

		GROUP BY CIT.DATAAREAID, CIT.RECID, CIT.INVENTTRANSID

	) AS CUSTO ON CUSTO.RECID = CIT.RECID AND CUSTO.DATAAREAID = CIT.DATAAREAID
	JOIN SALESLINE SL ON SL.INVENTTRANSID = CIT.INVENTTRANSID
	JOIN SALESTABLE ST ON ST.SALESID = SL.SALESID AND ST.DATAAREAID = SL.DATAAREAID
	JOIN SALESTABLE_BR ST_BR ON ST_BR.SALESTABLE = ST.RECID
	JOIN SALESPURCHOPERATIONTYPE_BR SPOT ON SPOT.RECID = ST_BR.SALESPURCHOPERATIONTYPE_BR

WHERE CIT.DATAAREAID = 'OMT'
 
--AND CIT.ITEMID = '008999' AND CIT.INVOICEID IN ('000005414', '000005352')

--ORDER BY 2