
-- ALTER VIEW [BiView].[ReceitaLiquida_OMT]  AS

SELECT 

	IT.ITEMID, IT.COSTGROUPID, ERC.NAME AS CATEGORIA, X.[Cliente - Segmento], 
	AVG(SGL.SALEGOAL), SUM(X.[Valor Fat. Bruto])
	
FROM 

(
SELECT top 100 * FROM BiView.ReceitaLiquida_Weloze
) 

AS X

JOIN INVENTTABLE IT ON IT.ITEMID = X.[Item - Código] AND IT.DATAAREAID = 'OMT'
JOIN ECORESPRODUCT ERP ON ERP.RECID = IT.PRODUCT
LEFT JOIN ECORESPRODUCTCATEGORY ERPC ON ERPC.PRODUCT = ERP.RECID
LEFT JOIN ECORESCATEGORY ERC ON ERC.RECID = ERPC.CATEGORY
LEFT JOIN ECORESCATEGORYHIERARCHY ERCH ON ERCH.RECID = ERC.CATEGORYHIERARCHY AND ERCH.NAME = 'LINHA DE PRODUTO OMT'

FULL JOIN SALEGOALLINE SGL ON SGL.SEGMENTID = X.[Cliente - Segmento] AND SGL.ECORESCATEGORYNAME = ERC.NAME
FULL JOIN SALEGOAL SG ON SG.YEAR = YEAR(X.Data)

GROUP BY IT.ITEMID, IT.COSTGROUPID, ERC.NAME, X.[Cliente - Segmento]

ORDER BY 3, 4