
-- ALTER VIEW [BiView].[MetaFaturamento_OMT]  AS

SELECT 

	X.[Data - Mês/Ano],

	ERC.NAME				AS "Item - Categoria", 
	X.[Cliente - Segmento]	AS "Cliente - Segmento", 

	AVG(SGL.AMOUNT)				/ 1000	AS "Meta", 
	SUM(X.[Valor Rec. Líquida])	/ 1000	AS "Faturado"
	
FROM (SELECT * FROM BI_Weloze.BiWeloze.ReceitaLiquida_OMT) AS X

JOIN INVENTTABLE IT ON IT.ITEMID = X.[Item - Código] AND IT.DATAAREAID = 'OMT'
JOIN ECORESPRODUCT ERP ON ERP.RECID = IT.PRODUCT
LEFT JOIN ECORESPRODUCTCATEGORY ERPC ON ERPC.PRODUCT = ERP.RECID
LEFT JOIN ECORESCATEGORY ERC ON ERC.RECID = ERPC.CATEGORY
LEFT JOIN ECORESCATEGORYHIERARCHY ERCH ON ERCH.RECID = ERC.CATEGORYHIERARCHY AND ERCH.NAME = 'LINHA DE PRODUTO OMT'

RIGHT JOIN SALEGOALLINE SGL ON SGL.SEGMENTID = X.[Cliente - Segmento] AND SGL.ECORESCATEGORYNAME = ERC.NAME
RIGHT JOIN SALEGOAL SG ON SG.RECID = SGL.SALEGOAL 

WHERE SG.YEAR = YEAR(X.Data) 

GROUP BY ERC.NAME, X.[Cliente - Segmento], X.[Data - Mês/Ano]