-- ALTER VIEW [BiView].[DiariosAtivosFixos_Nopin] AS 

SELECT 
	
	LJTA.JOURNALNUM								AS "Número do Diário", 
	LJTA.NAME	AS "Descrição do Diário", 
	LJTA.CREATEDBY			AS "Criador por",
	LJTA.MODIFIEDBY			AS "Modificado por",
	CASE WHEN LJTA.POSTEDDATETIME = '1900-01-01' THEN '' ELSE FORMAT(LJTA.POSTEDDATETIME, 'dd/MM/yyyy') END AS "Lançado em",

	COUNT(LJTR.RECID) AS "Qtd. de Linhas",

	SUM(LJTR.AMOUNTCURCREDIT)		AS "Valor Crédito", 
	SUM(LJTR.AMOUNTCURDEBIT)		AS "Valor Débito"

FROM LEDGERJOURNALTABLE LJTA
	JOIN LEDGERJOURNALTRANS LJTR ON LJTR.JOURNALNUM = LJTA.JOURNALNUM
	JOIN LEDGERJOURNALTRANS_ASSET LJTR_A ON LJTR_A.REFRECID = LJTR.RECID
WHERE LJTA.DATAAREAID = 'NBRA'

GROUP BY LJTA.JOURNALNUM, LJTA.NAME, LJTA.RECID, LJTA.CREATEDBY, LJTA.MODIFIEDBY, LJTA.POSTEDDATETIME


