
-- ALTER VIEW BiView.DiariosAtivosFixos_Nopin AS 

SELECT 
	
	LJTA.JOURNALNUM								AS "Número do Diário", 
	CONCAT(LJTA.NAME, ' RECID( ', LJTA.RECID, ' )')	AS "Descrição do Diário", 
	LJTA.CREATEDBY			AS "Criador por",
	LJTA.MODIFIEDBY			AS "Modificado por",
	LJTA.POSTEDDATETIME		AS "Lançado em",

	COUNT(LJTR.RECID) AS "Qtd. de Linhas",

	SUM(LJTR.AMOUNTCURCREDIT)		AS "Valor Crédito", 
	SUM(LJTR.AMOUNTCURDEBIT)		AS "Valor Débito"

FROM LEDGERJOURNALTABLE LJTA
	LEFT JOIN LEDGERJOURNALTRANS LJTR ON LJTR.JOURNALNUM = LJTA.JOURNALNUM
	LEFT JOIN LEDGERJOURNALTRANS_ASSET LJTR_A ON LJTR_A.REFRECID = LJTR.RECID
WHERE LJTA.DATAAREAID = 'NBRA'

GROUP BY LJTA.JOURNALNUM, LJTA.NAME, LJTA.RECID, LJTA.CREATEDBY, LJTA.MODIFIEDBY, LJTA.POSTEDDATETIME
