
-- ALTER VIEW BiView.LancamentosOrdensProducao_OMT AS 

SELECT 
	
	CONCAT(PT.PRODID, ' - ', IT.ITEMID, ' ', ERPT.NAME) AS "Ordem de Produção ",
	FORMAT(PT.CREATEDDATETIME, 'dd/MM/yyyy') AS "Data de Criação ",
	FORMAT(PT.CREATEDDATETIME, 'yyyy/MM') AS "Data de Criação (Mês/Ano) ",
	PT.CREATEDBY AS "Criado por ",
	OP_STATUS.STATUS AS "Status ",
	
	AVG(PT.QTYCALC) AS "Qtd. Ordem ",
	COUNT(PJT_LS.RECID) AS "Qtd. de diários "

FROM PRODTABLE PT
	JOIN INVENTTABLE IT ON IT.ITEMID = PT.ITEMID AND IT.DATAAREAID = PT.DATAAREAID
	JOIN ECORESPRODUCT ERP ON ERP.RECID = IT.PRODUCT
	JOIN ECORESPRODUCTTRANSLATION ERPT ON ERPT.PRODUCT = ERP.RECID AND ERPT.LANGUAGEID = 'PT-BR'
	LEFT JOIN PRODJOURNALTABLE PJT_LS ON PJT_LS.PRODID = PT.PRODID AND PJT_LS.DATAAREAID = PT.DATAAREAID AND PJT_LS.JOURNALTYPE = 0
	CROSS APPLY BiUtil.StatusOrdemProducao(PT.PRODSTATUS) OP_STATUS

WHERE PT.DATAAREAID = 'OMT'

GROUP BY PT.PRODID, IT.ITEMID, ERPT.NAME, PT.CREATEDDATETIME, PT.CREATEDBY, PT.QTYCALC, OP_STATUS.STATUS