
ALTER FUNCTION BiUtil.ImpostoPorGrupos (@Empresa VARCHAR(5), @GrupoImposto VARCHAR(10), @GrupoImpostoItem VARCHAR(10), @CodigoImposto INTEGER, @Valor FLOAT) 
RETURNS TABLE AS

	RETURN (
		SELECT COALESCE(VALOR - (VALOR * REDUCAO / 100), 0) AS PERCENTUAL,  COALESCE((VALOR - (VALOR * REDUCAO / 100)) * @Valor / 100, 0) AS VALOR FROM
		(
			SELECT MAX(VALOR) VALOR, MIN(REDUCAO) REDUCAO FROM 
			(
				SELECT IGL.TAXCODE AS IMPOSTO, D.TAXVALUE AS VALOR, D.TAXREDUCTIONPCT_BR AS REDUCAO FROM TAXGROUPHEADING IG
					JOIN TAXGROUPDATA IGL ON IGL.TAXGROUP = IG.TAXGROUP AND IG.DATAAREAID = IGL.DATAAREAID
					JOIN TAXTABLE T ON T.TAXCODE = IGL.TAXCODE
					JOIN TAXDATA D ON D.TAXCODE = T.TAXCODE AND D.DATAAREAID = T.DATAAREAID
				WHERE IG.DATAAREAID = @Empresa
				AND IG.TAXGROUP = @GrupoImposto
				AND T.TAXTYPE_BR IN (@CodigoImposto)

				INTERSECT

				SELECT IIL.TAXCODE AS IMPOSTO, D.TAXVALUE AS VALOR, D.TAXREDUCTIONPCT_BR AS REDUCAO FROM TAXITEMGROUPHEADING II
					JOIN TAXONITEM IIL ON IIL.TAXITEMGROUP = II.TAXITEMGROUP AND II.DATAAREAID = IIL.DATAAREAID
					JOIN TAXTABLE T ON T.TAXCODE = IIL.TAXCODE 
					JOIN TAXDATA D ON D.TAXCODE = T.TAXCODE AND D.DATAAREAID = T.DATAAREAID
				WHERE II.DATAAREAID = @Empresa
				AND II.TAXITEMGROUP = @GrupoImpostoItem
				AND T.TAXTYPE_BR IN (@CodigoImposto)
		) AS X
		GROUP BY X.IMPOSTO
		) AS Y
	);
