
ALTER FUNCTION [BiUtil].TaxaCambioNaData (@Data DATE, @MoedaEstrangeira VARCHAR(5))
RETURNS TABLE
AS
RETURN 
(
	SELECT (ER.EXCHANGERATE / 100.0 * FATOR.VALOR) AS TAXA, ER.VALIDFROM AS VALIDODE, ER.VALIDTO AS VALIDOATE FROM EXCHANGERATECURRENCYPAIR ERCP
		JOIN EXCHANGERATE ER ON ER.EXCHANGERATECURRENCYPAIR = ERCP.RECID
		JOIN EXCHANGERATETYPE ERT ON ERT.RECID = ERCP.EXCHANGERATETYPE
		CROSS APPLY biweloze.FatorExibicaoTaxaCambio(ERCP.EXCHANGERATEDISPLAYFACTOR) AS FATOR
	WHERE TOCURRENCYCODE = 'BRL' AND ERT.NAME = 'Padrão'
		AND @Data BETWEEN ER.VALIDFROM AND ER.VALIDTO
		AND ERCP.FROMCURRENCYCODE = @MoedaEstrangeira
)
