
-- ALTER VIEW BiView.TodasNotasFiscais_Weloze AS
	
SELECT

	NF.DATAAREAID	AS "EMPRESA",
		
	CASE WHEN NF.DIRECTION = 1 THEN 'ENTRADA' ELSE 'SAÍDA' END AS "DIREÇÃO", 

	NF.FISCALESTABLISHMENTNAME	AS "FILIAL", 
	NF.ACCESSKEY				AS "CHAVE DE ACESSO",
	NF.FISCALDOCUMENTNUMBER		AS "NÚMERO", 
	NF.FISCALDOCUMENTSERIES		AS "SÉRIE", 
	NF.THIRDPARTYNAME			AS "TERCEIRO", 
	TERCEIRO.STATE				AS "ESTADO - TERCEIRO",
	ENTREGA.STATE				AS "ESTADO - ENTREGA",
	ESTABEL.STATE				AS "ESTADO - FILIAL",
	NF.FISCALDOCUMENTDATE		AS "DATA DOCUMENTO",
	NF.ACCOUNTINGDATE			AS "DATA LANÇAMENTO",
	LNF.ITEMID					AS "PRODUTO", 
	LNF.DESCRIPTION				AS "DESCRIÇÃO",
	LNF.UNIT					AS "UNIDADE DE MEDIDA",
	LNF.FISCALCLASSIFICATION	AS "NCM",
	LNF.CFOP					AS "CFOP",
	LNF.QUANTITY				AS "QUANTIDADE",
	LNF.LINEAMOUNT				AS "VALOR",
	LNF.LINEDISCOUNT			AS "DESCONTO",
	LNF.LINEAMOUNT - LNF.LINEDISCOUNT	AS "VALOR CONTÁBIL",

	IPI.TAXATIONCODE	AS "IPI CST",
	IPI.TAXBASEAMOUNT	AS "IPI BASE",
	IPI.TAXVALUE		AS "IPI ALÍQUOTA",
	IPI.TAXAMOUNT		AS "IPI VALOR",

	ICM.TAXATIONCODE	AS "ICMS CST",
	ICM.TAXBASEAMOUNT	AS "ICMS BASE",
	ICM.TAXVALUE		AS "ICSM ALÍQUOTA",
	ICM.TAXAMOUNT		AS "ICMS VALOR",

	DIF.TAXATIONCODE	AS "DIFAL CST",
	DIF.TAXBASEAMOUNT	AS "DIFAL BASE",
	DIF.TAXVALUE		AS "DIFAL ALÍQUOTA",
	DIF.TAXAMOUNT		AS "DIFAL VALOR",

	PIS.TAXATIONCODE	AS "PIS CST",
	PIS.TAXBASEAMOUNT	AS "PIS BASE",
	PIS.TAXVALUE		AS "PIS ALÍQUOTA",
	PIS.TAXAMOUNT		AS "PIS VALOR",

	COF.TAXATIONCODE	AS "COFINS CST",
	COF.TAXBASEAMOUNT	AS "COFINS BASE",
	COF.TAXVALUE		AS "COFINS ALÍQUOTA",
	COF.TAXAMOUNT		AS "COFINS VALOR"

FROM FISCALDOCUMENT_BR NF
	JOIN FISCALDOCUMENTLINE_BR LNF ON LNF.FISCALDOCUMENT = NF.RECID

	LEFT JOIN FISCALDOCUMENTTAXTRANS_BR IPI ON IPI.FISCALDOCUMENTLINE = LNF.RECID AND IPI.TYPE = 8
	LEFT JOIN FISCALDOCUMENTTAXTRANS_BR PIS ON PIS.FISCALDOCUMENTLINE = LNF.RECID AND PIS.TYPE = 1
	LEFT JOIN FISCALDOCUMENTTAXTRANS_BR ICM ON ICM.FISCALDOCUMENTLINE = LNF.RECID AND ICM.TYPE = 2
	LEFT JOIN FISCALDOCUMENTTAXTRANS_BR COF ON COF.FISCALDOCUMENTLINE = LNF.RECID AND COF.TYPE = 3
	LEFT JOIN FISCALDOCUMENTTAXTRANS_BR DIF ON DIF.FISCALDOCUMENTLINE = LNF.RECID AND DIF.TYPE = 15

	LEFT JOIN LOGISTICSPOSTALADDRESS ENTREGA	ON ENTREGA.RECID =	NF.DELIVERYLOGISTICSPOSTALADDRESS
	LEFT JOIN LOGISTICSPOSTALADDRESS TERCEIRO	ON TERCEIRO.RECID = NF.THIRDPARTYPOSTALADDRESS
	LEFT JOIN LOGISTICSPOSTALADDRESS ESTABEL	ON ESTABEL.RECID =	NF.FISCALESTABLISHMENTPOSTALADDRESS

WHERE NF.DATAAREAID = 'WELO' AND NF.STATUS = 1