
-- ALTER VIEW BiView.RequisitosLiquidos_OMT  AS 

 SELECT 
	REQ.RECID AS REQ_RECID, 
	REQ.REFID AS REQ_REFID, 
	REQ.REFTYPE AS REQ_REFTYPE, 
	REQ.ACTIONTYPE AS REQ_ACTIONTYPE,
	ATE.RECID AS ATE_RECID, 
	ATE.REFID AS ATE_REFID, 
	ATE.REFTYPE AS ATE_REFTYPE, 
	ATE.ACTIONTYPE AS ATE_ACTIONTYPE,
	COV.ITEMID
FROM REQTRANS REQ
	JOIN (
		SELECT RECEIPTRECID, ISSUERECID, ITEMID FROM REQTRANSCOV
		WHERE DATAAREAID = 'OMT'
		GROUP BY RECEIPTRECID, ISSUERECID, ITEMID
	) AS COV ON COV.RECEIPTRECID = REQ.RECID
	JOIN REQTRANS ATE ON ATE.RECID = COV.ISSUERECID